__Pandas-DataFrame And Series__

Pandas is a powerful data manipulation library in python, widely used for data analysis and data cleaning. It provides two primary data structures: Series and DataFrame. A series is a one-dimensional array-like object, while a Dataframe is a two dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns)

In [2]:
pip install pandas

Requirement already satisfied: pandas in c:\users\asus\downloads\python\venv\lib\site-packages (2.3.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\asus\downloads\python\venv\lib\site-packages (from pandas) (2.3.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\asus\downloads\python\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\asus\downloads\python\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\asus\downloads\python\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\asus\downloads\python\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

In [6]:
## Series
## pandas series is a one-dimensional array-like object that can hold any data type. It is similar to column in a table

import pandas as pd
data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n", series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
### create as series from dictionary

data={'a':1, 'b':2, 'c':3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [9]:
data=[10,20,30]
index=['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [11]:
## Data frame
## create a Dataframe from a dictionary of list

data={
    'Name':['Krish', 'John', 'Jack'],
    'Age': [25,30,45],
    'City':['Bangalore', 'New york', 'Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   25  Bangalore
1   John   30   New york
2   Jack   45    Florida
<class 'pandas.core.frame.DataFrame'>

In [12]:
import numpy as np
np.array(df)

array([['Krish', 25, 'Bangalore'],
       ['John', 30, 'New york'],
       ['Jack', 45, 'Florida']], dtype=object)

In [14]:
## Create a Data frame from a list of Dictionaries

data=[
    {'Name': 'Krish', 'Age':32, 'City':'Bangalore'},
    {'Name': 'jphn', 'Age':32, 'City':'florida'},
    {'Name': 'kelly', 'Age':52, 'City':'minnesota'},

]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   jphn   32    florida
2  kelly   52  minnesota
<class 'pandas.core.frame.DataFrame'>

In [16]:
df=pd.read_csv('online_sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet

In [18]:
### Accessing DATA FROM DATAFRAME

df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet

In [20]:
df['Date']

0    2025-09-15
1    2025-09-16
2    2025-09-17
3    2025-09-18
4    2025-09-19
Name: Date, dtype: object

In [21]:
df.iloc[0]

Transaction ID                 T1001
Date                      2025-09-15
Product Category         Electronics
Product Name        Wireless Earbuds
Units Sold                         3
Unit Price                     49.99
Total Revenue                 149.97
Region                         North
Payment Method           Credit Card
Name: 0, dtype: object

In [22]:
type(df(Date))

NameError: name 'Date' is not defined

In [27]:
df.iloc[0][2]

C:\Users\ASUS\AppData\Local\Temp\ipykernel_16156\2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Electronics'

In [29]:
## Accessing a specified element

df['Date']

0    2025-09-15
1    2025-09-16
2    2025-09-17
3    2025-09-18
4    2025-09-19
Name: Date, dtype: object

In [30]:
df.at[1,'Region']

'West'

In [31]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet

In [32]:
df.at[2,'Product Name']

"Men's T-Shirt"

In [35]:
## accessing a specified element using iat
df.iat[3,3]

'Data Science Handbook'

In [36]:
## Data manipulation with dataframe
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet

In [38]:
df['Ecommerce Platform']=['Amazon', 'Flipkart', 'Blinkit', 'Instamart', 'Zepto']

In [39]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Ecommerce Platform
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card,Amazon
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet,Zepto

In [41]:
## Remove a column
df.drop('Region',axis=7)

ValueError: No axis named 7 for object type DataFrame

In [42]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method,Ecommerce Platform
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card,Amazon
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet,Zepto

In [46]:
#Remove a column
df.drop('Region',axis=1,inplace=True)

KeyError: "['Region'] not found in axis"

In [44]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Ecommerce Platform
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,Credit Card,Amazon
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Digital Wallet,Zepto

In [47]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Ecommerce Platform
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,Credit Card,Amazon
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Digital Wallet,Zepto

In [49]:
## Add increment to the column
df['Total Revenue']=df['Total Revenue']+1

In [50]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Ecommerce Platform
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,150.97,Credit Card,Amazon
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,128.50,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,130.90,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,91.00,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,76.00,Digital Wallet,Zepto

In [51]:
df.drop(0)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Ecommerce Platform
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,128.5,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,130.9,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,91.0,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,76.0,Digital Wallet,Zepto

In [52]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Ecommerce Platform
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,150.97,Credit Card,Amazon
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,128.50,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,130.90,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,91.00,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,76.00,Digital Wallet,Zepto

In [53]:
df.drop(0,inplace=True)

In [54]:
df

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Payment Method,Ecommerce Platform
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,128.5,UPI,Flipkart
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,130.9,Cash,Blinkit
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,91.0,Debit Card,Instamart
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,76.0,Digital Wallet,Zepto

In [56]:
df=pd.read_csv('online_sales_data.csv')
df.head(5)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,T1001,2025-09-15,Electronics,Wireless Earbuds,3,49.99,149.97,North,Credit Card
1,T1002,2025-09-16,Home & Kitchen,Electric Kettle,5,25.50,127.50,West,UPI
2,T1003,2025-09-17,Clothing,Men's T-Shirt,10,12.99,129.90,South,Cash
3,T1004,2025-09-18,Books,Data Science Handbook,2,45.00,90.00,East,Debit Card
4,T1005,2025-09-19,Beauty,Moisturizing Cream,4,18.75,75.00,Central,Digital Wallet

In [58]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the dataframe
print("Satistical summary:\n", df.describe())

#Group by a column and perform an aggregation
grouped = df.groupby('Category')['Value'].mean()
print("Mean value by category:\n", grouped)

Data types:
 Transaction ID       object
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object
Satistical summary:
        Units Sold  Unit Price  Total Revenue
count    5.000000    5.000000       5.000000
mean     4.800000   30.446000     114.474000
std      3.114482   16.276963      30.922393
min      2.000000   12.990000      75.000000
25%      3.000000   18.750000      90.000000
50%      4.000000   25.500000     127.500000
75%      5.000000   45.000000     129.900000
max     10.000000   49.990000     149.970000

KeyError: 'Category'

In [59]:
df.describe()

       Units Sold  Unit Price  Total Revenue
count    5.000000    5.000000       5.000000
mean     4.800000   30.446000     114.474000
std      3.114482   16.276963      30.922393
min      2.000000   12.990000      75.000000
25%      3.000000   18.750000      90.000000
50%      4.000000   25.500000     127.500000
75%      5.000000   45.000000     129.900000
max     10.000000   49.990000     149.970000