__Data Manipulation and Analysis with Pandas__

Data manipulation and analysis are key tasks in any data science or data analysis project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform, extract insights from data. In this lesson, we will cover various data manipulation and analysis techniques using pandas.

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('data.csv')
## fetch the first five rows
df.head(5)

         Date        Category   Value             Product  Sales   Region
0  2025-04-02          Beauty   83.01  Moisturizing Cream     13  Central
1  2025-08-30          Beauty  488.10             Shampoo     20  Central
2  2025-01-20  Home & Kitchen  434.68             Blender     38     East
3  2025-05-30          Beauty   24.93  Moisturizing Cream     46     East
4  2025-05-27           Books   41.31               Novel      7  Central

In [3]:
df.tail(5)

          Date        Category   Value             Product  Sales   Region
95  2025-09-10     Electronics  329.25          Smartwatch     21     West
96  2025-01-19          Beauty  467.06  Moisturizing Cream     48    North
97  2025-08-26  Home & Kitchen   16.00           Microwave     44    South
98  2025-04-28        Clothing  467.68              Jacket     15     East
99  2025-08-02     Electronics   22.96              Laptop     34  Central

In [4]:
df.describe()

            Value       Sales
count  100.000000  100.000000
mean   241.569600   26.160000
std    146.432389   13.977413
min     13.010000    1.000000
25%    141.945000   14.500000
50%    224.675000   27.500000
75%    363.112500   38.250000
max    495.840000   49.000000

In [5]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales         int64
Region       object
dtype: object

In [9]:
## Handling missing values
df.isnull().any()

Date        False
Category    False
Value       False
Product     False
Sales       False
Region      False
dtype: bool

In [10]:
df.isnull().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [11]:
df.isnull().sum()

Date        0
Category    0
Value       0
Product     0
Sales       0
Region      0
dtype: int64

In [12]:
df_filled=df.fillna(0)

In [14]:
## filling missing values with the mean of the column
df['Sales_fillNA']=df['Sales'].fillna(df['Sales'].mean())
df

,Date,Category,Value,Product,Sales,Region,Sales_fillNA
0,2025-04-02,Beauty,83.01,Moisturizing Cream,13,Central,13
1,2025-08-30,Beauty,488.10,Shampoo,20,Central,20
2,2025-01-20,Home & Kitchen,434.68,Blender,38,East,38
3,2025-05-30,Beauty,24.93,Moisturizing Cream,46,East,46
4,2025-05-27,Books,41.31,Novel,7,Central,7
...,...,...,...,...,...,...,...
95,2025-09-10,Electronics,329.25,Smartwatch,21,West,21
96,2025-01-19,Beauty,467.06,Moisturizing Cream,48,North,48
97,2025-08-26,Home & Kitchen,16.00,Microwave,44,South,44
98,2025-04-28,Clothing,467.68,Jacket,15,East,15
99,2025-08-02,Electronics,22.96,Laptop,34,Central,34

In [17]:
## Renaming columns
df=df.rename(columns={'Date': 'Sale Date'})
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA
0,2025-04-02,Beauty,83.01,Moisturizing Cream,13,Central,13
1,2025-08-30,Beauty,488.10,Shampoo,20,Central,20
2,2025-01-20,Home & Kitchen,434.68,Blender,38,East,38
3,2025-05-30,Beauty,24.93,Moisturizing Cream,46,East,46
4,2025-05-27,Books,41.31,Novel,7,Central,7

In [18]:
## change datatypes
df['Value_new']=df['Value'].astype(float)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new
0,2025-04-02,Beauty,83.01,Moisturizing Cream,13,Central,13,83.01
1,2025-08-30,Beauty,488.10,Shampoo,20,Central,20,488.10
2,2025-01-20,Home & Kitchen,434.68,Blender,38,East,38,434.68
3,2025-05-30,Beauty,24.93,Moisturizing Cream,46,East,46,24.93
4,2025-05-27,Books,41.31,Novel,7,Central,7,41.31

In [21]:
df['New value']=df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNA,Value_new,New value
0,2025-04-02,Beauty,83.01,Moisturizing Cream,13,Central,13,83.01,166.02
1,2025-08-30,Beauty,488.10,Shampoo,20,Central,20,488.10,976.20
2,2025-01-20,Home & Kitchen,434.68,Blender,38,East,38,434.68,869.36
3,2025-05-30,Beauty,24.93,Moisturizing Cream,46,East,46,24.93,49.86
4,2025-05-27,Books,41.31,Novel,7,Central,7,41.31,82.62

In [23]:
## Data Aggregating and grouping
grouped_mean=df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Action Figure            170.786667
Basketball               260.837500
Biography                474.555000
Blender                  298.156000
Board Game                93.330000
Cookbook                  90.628333
Data Science Handbook    302.528000
Doll                      76.670000
Electric Kettle          240.445000
Football                 350.042500
Jacket                   221.193333
Jeans                    124.900000
Laptop                   200.186667
Lipstick                 221.186667
Men's T-Shirt            200.226667
Microwave                226.075714
Moisturizing Cream       248.038000
Novel                    211.620000
Perfume                  471.340000
Puzzle                   191.742500
Shampoo                  316.220000
Smartphone               254.610000
Smartwatch               204.855000
Tennis Racket            371.357500
Toaster                  263.688000
Wireless Earbuds         251.236667
Women's Dress            302.980000
Yoga Mat                 185.340000
Name: Value, dtype: float64

In [25]:
grouped_sum=df.groupby(['Product', 'Region'])['Value'].sum()
print(grouped_sum)

Product           Region
Action Figure     Central     34.00
                  North      275.01
                  West       203.35
Basketball        East       361.14
                  North      391.81
                              ...
Wireless Earbuds  West       273.91
Women's Dress     Central    167.80
                  North      371.97
                  South      369.17
Yoga Mat          Central    185.34
Name: Value, Length: 76, dtype: float64

In [26]:
df.groupby(['Product', 'Region'])['Value'].sum()

Product           Region
Action Figure     Central     34.00
                  North      275.01
                  West       203.35
Basketball        East       361.14
                  North      391.81
                              ...
Wireless Earbuds  West       273.91
Women's Dress     Central    167.80
                  North      371.97
                  South      369.17
Yoga Mat          Central    185.34
Name: Value, Length: 76, dtype: float64

In [27]:
## aggregate multiple functions
grouped_agg=df.groupby('Region')['Value'].agg(['mean','sum','count'])
grouped_agg

               mean      sum  count
Region
Central  219.105000  4382.10     20
East     255.288095  5361.05     21
North    259.635263  4933.07     19
South    221.860000  3993.48     18
West     249.420909  5487.26     22

In [28]:
## merging and joining Dataframes
# created sample dataframes

df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1,2,3]})
df2 = pd.DataFrame({'Key': ['A','B','D'], 'Value2': [4, 5, 6]})

In [29]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [30]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

In [31]:
## merge Dataframe on the key columns
pd.merge(df1, df2, on="Key", how="inner")

  Key  Value1  Value2
0   A       1       4
1   B       2       5

In [32]:
pd.merge(df1, df2, on="Key", how="outer")

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

In [34]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

In [35]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN